### ISSUE TITLE
ra/SAPHANA* - remove redundant HDBSettings.sh calls

### ISSUE THREAD

**Issue by PeterPitterling** [SUSE/SAPHanaSR#116]
currently all HANA_CALL executions are prefixed by "su - sidadm"

User login shell is already executing HDBSettings.sh and therefore additional call ' /usr/sap/XXX/HDB00/HDBSettings.sh' is redundant.
HDBSettings.sh is sourcing/calling additional scripts, which all do their initial executions. As these calls are executed almost every 2-3s within a cluster environment this is creating a lot of unnecessary filesystem activities.

```console
su - xxxadm -c '(true; timeout -s 9 10 /usr/sap/XXX/HDB00/HDBSettings.sh HDB version'
su - xxxadm -c '(true; timeout -s 9 120 /usr/sap/XXX/HDB00/HDBSettings.sh hdbnsutil -sr_stateConfiguration'
su - xxxadm -c '(true; timeout -s 9 120 /usr/sap/XXX/HDB00/HDBSettings.sh landscapeHostConfiguration.py'
su - xxxadm -c '(true; timeout -s 9 5 /usr/sap/XXX/HDB00/HDBSettings.sh systemReplicationStatus.py --site=SiteB'
and more
```

As long as su - sidadm is anyway the default and cannot be changed by script parameters simply remove the redundant call.

**Comment by fmherschel** [comment]
In my SAP HANA installation I can't see that HDBSettings.sh is been started, if I call a "su - sidadm -c 'command' ".

**Comment by PeterPitterling** [comment]
> In my SAP HANA installation I can't see that HDBSettings.sh is been started, if I call a "su - sidadm -c 'command' ".

sidadm home (/usr/sap/<SID>/home) directory --> .profile --> .bashrc --> .sapenv.sh

```bash
# execute instance settings and change to instance dir
. /usr/sap/$SAPSYSTEMNAME/HDB[0-9][0-9]/HDBSettings.sh
cd /usr/sap/$SAPSYSTEMNAME/HDB[0-9][0-9]
```

**Comment by PeterPitterling** [comment]
> @PeterPitterling maybe I did misunderstand your tipp. The following works: su - ha1adm -c "HDBSettings.sh landscapeHostConfiguration.py"
> 
> These calls are not working: su - ha1adm -c "landscapeHostConfiguration.py" su - ha1adm "landscapeHostConfiguration.py" su - ha1adm -c "python landscapeHostConfiguration.py"
> 
> The following would work: su - ha1adm -c "python exe/python_support/landscapeHostConfiguration.py"

Yes, the python scripts are stored within python_support. There is an alias cdpy set by the SAP environment, therefore this also works:

`su - ha1adm -c 'cdpy; python landscapeHostConfiguration.py'`

**Comment by fmherschel** [comment]
Yes using cdpy is an option (tested also on my system). I did know cdpy already but it did not work in one of my scripts in the past. But this script was not running though the chain of .profile->.bashrc->.sapenv.sh so the alias was not set. But here while using su - <sid>adm it works properly. And I could rely on "cdpy" in the same way as we relied on "HDBSettings.sh". I just wanted to avoid to code-in paths like 'exe/python_support", because they could be changed by SAP.
With su - sidadm -c 'cdpy; python <python-script>' we ave in deed a good option.
Please do not expect that we can change the sources very quickly (and thus not official packages), because I am currently in an other project. This github issue will help us not to forget this.

**Comment by PeterPitterling** [comment]
FOR COMPLETNESS

> The following works: su - ha1adm -c "HDBSettings.sh landscapeHostConfiguration.py"
> These calls are not working: 
> su - ha1adm -c "landscapeHostConfiguration.py" 
> su - ha1adm "landscapeHostConfiguration.py" 
> su - ha1adm -c "python landscapeHostConfiguration.py"
>
> The following would work: su - ha1adm -c "python exe/python_support/landscapeHostConfiguration.py"


hdbenv.sh

```shell
DIR_INSTANCE=/usr/sap/"$SAPSYSTEMNAME"/HDB"$TINSTANCE"
DIR_EXECUTABLE=$DIR_INSTANCE/exe

  elif [ x`basename $1 .py`.py = x`basename $1` ] ; then
    cd $DIR_EXECUTABLE/python_support
    python "$@"
```

**Comment by PeterPitterling** [comment]
> I just wanted to avoid to code-in paths like 'exe/python_support", because they could be changed by SAP. 

You have that dependency already in the script
https://github.com/SUSE/SAPHanaSR/blob/fabfd379ced69f40679b5cc53758b18b7ec6784a/ra/SAPHana#L2512-L2516
