### ISSUE TITLE
SAPHanaTopology fails to stop successfuly

### ISSUE THREAD

**Issue by fmherschel** [SUSE/SAPHanaSR#162]
SAPHanaTopology fails to stop successfuly
Ends up with error code 1 (OCF_ERR_GENERIC)

**Comment by angelabriel** [comment]
The same code line in ScaleOut is ok. Thanks for the close monitoring of the changes and spotting this missing piece of the last code refactoring.

**Comment by fmherschel** [comment]
> The same code line in ScaleOut is ok.
This might also be the case why in ANGI this bug was not visible any more ;-)

**Comment by angelabriel** [comment]
package SAPHanaSR 0.162.1 containing the fix for this issue is released
