### ISSUE TITLE
"we didn't expect node_status to be: DUMP <00000000  0a                                                |.|#01200000001>" 

### ISSUE THREAD

**Issue by PeterPitterling** [SUSE/SAPHanaSR#203]
Whenever we see the output "we didn't expect node_status to be: DUMP" it is always (>99%) exactly this output:

"we didn't expect node_status to be: DUMP <00000000  0a                                                |.|#01200000001>" 

<00000000  0a                                                |.|#01200000001>
is created by the hexdump -C call

https://github.com/SUSE/SAPHanaSR/blob/83ddf5722e1eefbd836daf9002f79d68a84513a3/ra/SAPHana#L1276-L1282

|.| just means "non-printable char"
`#0120` just means \n (caused by rsyslog which is used by super-ocf-log)
https://stackoverflow.com/questions/24606757/rsyslogd-and-characters-012-and-015
The characters \n and \r are dumped as #012 and #015 in the log file 

Therefore the DUMP output above just means LF 
00000000 \n
00000001

so the command just returned an empty string.

These special case should be treated seperately and instead of printint the DUMP .. the output should just mention, that an empty result was returned.

**Comment by PeterPitterling** [comment]
here is an easy reproducer (wrong path --key=global.ini2 used)

```console
#!/bin/bash

gpKeys=$(echo --key=global.ini2/system_replication/{mode,site_name,site_id})

hdbANSWER=$(su - tqladm -c /usr/sap/TQL/HDB00/HDBSettings.sh getParameter.py  $gpKeys --sapcontrol=1 2>&1 | awk -F/ 'BEGIN {out=0} /^SAPCONTROL-OK: <begin>/ { out=1 } /^SAPCONTROL-OK: <end>/ { out=0 } /=/ {if (out==1) {print $3} }')
srmode=$(echo "$hdbANSWER" | awk -F= '$1=="mode" {print $2}')
dump=$(echo $srmode | hexdump -C)

logger -t "DUMP" "${dump}"
```

leads to this output in /var/log/messages

 # grep DUMP /var/log/messages
2023-09-28T15:00:37.189200+02:00 host1 DUMP: 00000000  0a                                                |.|#01200000001

**Comment by fmherschel** [comment]
dump=$(echo $srmode | hexdump -C)

So the 0x0a comes from the last echo and we could simply check for an empty srmode.

Thanks
Fabian

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
