### ISSUE TITLE
Adjust default operation timeouts in SAPHana and SAPHanaTopology resource agents?

### ISSUE THREAD

**Issue by fdanapfel** [SUSE/SAPHanaSR#33]
Currently the defaults for the operation timeouts for both resource agents are set to low values compared to the values that are given as recommenations in all the documentation from SUSE, Red Hat and others:
- defaults in SAPHana resource agent:
```
    <action name="start"   timeout="180" />
    <action name="stop"    timeout="240" />
    <action name="status"  timeout="60" />
    <action name="monitor" depth="0" timeout="60" interval="120" />
    <action name="monitor" depth="0" timeout="60" interval="121" role="Slave" />
    <action name="monitor" depth="0" timeout="60" interval="119" role="Master" />
    <action name="promote" timeout="320" />
    <action name="demote"  timeout="320" />
```

- defaults defined SAPHanaTopology resource agent:
```
    <action name="start" timeout="180" />
    <action name="stop" timeout="60" />
    <action name="status" timeout="60" />
    <action name="monitor" depth="0" timeout="60" interval="60" />
```
The values to use given in the documentation are usually much higher, for example here are values given by Microsoft when setting up HANA System Replication HA on SLES on Azure:
```
sudo crm configure primitive rsc_SAPHanaTopology_HN1_HDB03 ocf:suse:SAPHanaTopology \
  operations \$id="rsc_sap2_HN1_HDB03-operations" \
  op monitor interval="10" timeout="600" \
  op start interval="0" timeout="600" \
  op stop interval="0" timeout="300" \
  params SID="HN1" InstanceNumber="03"
```
```
sudo crm configure primitive rsc_SAPHana_HN1_HDB03 ocf:suse:SAPHana \
  operations \$id="rsc_sap_HN1_HDB03-operations" \
  op start interval="0" timeout="3600" \
  op stop interval="0" timeout="3600" \
  op promote interval="0" timeout="3600" \
  op monitor interval="60" role="Master" timeout="700" \
  op monitor interval="61" role="Slave" timeout="700" \
  params SID="HN1" InstanceNumber="03" PREFER_SITE_TAKEOVER="true" \
  DUPLICATE_PRIMARY_TIMEOUT="7200" AUTOMATED_REGISTER="false"
```

We've seen a number of issues now where customers ran into issues because they forgot to explicitly define the values to use during resource creation, and then the cluster used the defaults defined in the resource agents, which led to cluster failures since the responses from the HANA instances took much longer than the timeouts currently set as defaults in the resource agents.

Also we've received questions from customers why the values recommended in the documentation are different from the defaults defined in the resource agents.

My suggestion therefore would be to change the default values for the operation timeouts in both resource agents to the values given as recommendations in customer facing documentation from SUSE, Red Hat and others.

In addition at least in the SAPHana resource agent there are some default timeouts defined for operations which are actually never used:
```
    <action name="monitor" depth="0" timeout="60" interval="120" />
    <action name="methods" timeout="5" />
```
The 'monitor' operation is only used for standard resources, but in case of master/slave resources it is not needed, since there are separate monitor operations for the master and the slave resource.

'methods' seems to refer to an internal function of the resource agent, which as far as I can see is never called from outside as an operation. Also I haven't seen any other resource agents where a timeout for a 'methods' operation is defined.

Therefore I'd suggest to remove these two definitions from the resource agent (the 'methods' timeout will most likely also have to be removed from the SAPHanaToploogy resource  agent).

**Comment by diegoakechi** [comment]
@fdanapfel the `actions` timeout values set on the metadata are not really defaults, but recommended values. The user still needs to configure them when creating the resources on the pacemaker configuration. Anyway, I agree that having different recommendations on different places can cause confusion, so I am ok to change it to the documented values. 

@fmherschel Do you see any reason to not do it?

**Comment by fmherschel** [comment]
> @fdanapfel the `actions` timeout values set on the metadata are not really defaults, but recommended values. The user still needs to configure them when creating the resources on the pacemaker configuration. Anyway, I agree that having different recommendations on different places can cause confusion, so I am ok to change it to the documented values.
> 
> @fmherschel Do you see any reason to not do it?

AFAIK customers will still be able to set lower numbers, if they need to do it. The only negative
impact would be that those customers would get a warning (at least in crmsh). So I would vote to
change the defaults. 

SAPHana:  
Start, Stop and Promote should be default to 3600
Monitor (slave) and Monitor (master) should be default to 700

SAPHanaTopology:
Start and Monitor should default to 600
Stop should default to 300

These are the values from our last published SAP HANA best practice, also matching what Frank
wrote above.

@diegoakechi: What are the real action defaults, if the definitions from the metadata are not sufficient? Could we figure out the time values while running SAPHana (SAPHanaTopology) and writing a message, if the RA would be started with action f.e. validate-all? Then the customer would have a chance to check, if he/she fits the minimum values.

**Comment by fdanapfel** [comment]
> @fdanapfel the `actions` timeout values set on the metadata are not really defaults, but recommended values. The user still needs to configure them when creating the resources on the pacemaker configuration. Anyway, I agree that having different recommendations on different places can cause confusion, so I am ok to change it to the documented values.

As far as I know the pcs tool provided by Red Hat for managing pacemaker clusters is using the timeouts defined in the resource agents to configure the resource operation timeouts, unless the user hasn't explicitly specified the operation timeouts during resource creation.

@fmherschel: thanks for the approval. If it is OK with you I will go ahead and create a PR to get the values changed.

BTW what is the opinion from both of you on removing the 'methods' action timeout and the general 'monitor' timeout for the SAPHana resource agent?

**Comment by diegoakechi** [comment]
> > @fdanapfel the `actions` timeout values set on the metadata are not really defaults, but recommended values. The user still needs to configure them when creating the resources on the pacemaker configuration. Anyway, I agree that having different recommendations on different places can cause confusion, so I am ok to change it to the documented values.
> > @fmherschel Do you see any reason to not do it?
> 
> AFAIK customers will still be able to set lower numbers, if they need to do it. The only negative
> impact would be that those customers would get a warning (at least in crmsh). So I would vote to
> change the defaults.
> 
> SAPHana:
> Start, Stop and Promote should be default to 3600
> Monitor (slave) and Monitor (master) should be default to 700
> 
> SAPHanaTopology:
> Start and Monitor should default to 600
> Stop should default to 300
> 
> These are the values from our last published SAP HANA best practice, also matching what Frank
> wrote above.

@fdanapfel Do you intend to do a Pull request to change that?

> 
> @diegoakechi: What are the real action defaults, if the definitions from the metadata are not sufficient? 

Apart of the configuration on the resource level, the user can set a Global operation timeout that will be used by all resources without operation level configuration. If none of the 2 are configured, pacemaker has an internal 20s default timeout.

> Could we figure out the time values while running SAPHana (SAPHanaTopology) and writing a message, if the RA would be started with action f.e. validate-all? Then the customer would have a chance to check, if he/she fits the minimum values.

This would be possible, as pacemaker sets a global variable with the operation timeout (`OCF_RESKEY_CRM_meta_timeout`). For reference, I have used this on this PR: https://github.com/SUSE/SAPHanaSR/pull/11/files#diff-ee71895086bd579a0d399375b06f56f0R42

**Comment by fmherschel** [comment]
> @fmherschel: thanks for the approval. If it is OK with you I will go ahead and create a PR to get the values changed.

Yes, set me as reviewer and please also Angela @angelabriel 
 
> BTW what is the opinion from both of you on removing the 'methods' action timeout and the general 'monitor' timeout for the SAPHana resource agent?

The 'general' monitor timeout will be still needed *if* we would like to get rid of the M/S resource. 
The methods action is needed (AFAIK) for pacemaker to determine, which actions are implemented by the RA. Multiple major RAs are also defining the timeout like LVM, SAPDatabase and SAPInstance. So I would keep that one to.

**Comment by fdanapfel** [comment]
> @fdanapfel Do you intend to do a Pull request to change that?
 
@diegoakechi: yes, I just created https://github.com/SUSE/SAPHanaSR/pull/34

**Comment by fdanapfel** [comment]
Closing this issue since the associated PR has been merged.

@diegoakechi, @fmherschel, thanks a lot for your guidance and support!
