### ISSUE TITLE
HANA_CALL_TIMEOUT can't be configured in cluster configuration

### ISSUE THREAD

**Issue by fdanapfel** [SUSE/SAPHanaSR#36]
With commits https://github.com/SUSE/SAPHanaSR/commit/c618d8f77d95067505180d9f23881c15d0431988 and https://github.com/SUSE/SAPHanaSR/commit/4d7057b60cdbac9ec48fc61816a2c7afd1695ccd the option to make the internal timeout used for some of the calls of SAP HANA commands configurable was introduced.

Even though there is a description of the HANA_CALL_TIMEOUT parameter in the metadata of the resource agents the parameter currently can't be set via the cluster configuration, since there is no 'link' between OCF_RESKEY_HANA_CALL_TIMEOUT and the internal HANA_CALL_TIMEOUT variable. In fact HANA_CALL_TIMEOUT still gets hardcoded to 60 seconds.

Is this intentional? 

If yes it might be better to remove the description of the HANA_CALL_TIMEOUT parameter form the metadata to avoid customers trying to set it and then wondering why it doesn't work.

**Comment by fmherschel** [comment]
Your idea is valid. However I want to discuss that with some of my colleagues. Background is (you might remember such discussions with the former maintainer of SAPInstance :) it is easy to add a new parameter to the RA but you never get rid of it once it has been published, as you always need to be concerned that someone did have used it even if you did not recommend to use it.

Second there is (maybe) an alternative available to use a calculated (aka flexible) HANA_CALL_TIMEOUT. This variant calculates the timeout from the cluster-operation-timeout. While the first one would be more direct and precise the second would be more elegant and matching to the already given parameters. Thus I decided to first stay with a fix hardcoded value which (at least) could be changed by changing one single line.

**Comment by fmherschel** [comment]
@fdanapfel Any feedback on this one? Should we discuss that issue also directly (1:1)?

**Comment by fdanapfel** [comment]
@fmherschel Yes, since we've had quite a few questions about this, it would be could if we could have a direct discussion on how to proceed with this issue.

**Comment by nrwahl2** [comment]
If discussion is likely to take a while, then I would strongly prefer to see this item removed from the RA metadata in the meantime. I provide customer-facing tech support for these agents, and this has caused confusion both for us and for our customers. I appreciate Frank pointing out to us that the parameter isn't actually implemented/connected.

It would be a simple matter to stop advertising this as an option until/unless we decide to fully implement it.

**Comment by fmherschel** [comment]
We take the HANA_CALL_TIMEOUT to the next major realease where we plan to align Scale-Up and Scale-Out.

**Comment by fdanapfel** [comment]
> We take the HANA_CALL_TIMEOUT to the next major realease where we plan to align Scale-Up and Scale-Out.

@fmherschel Do you mean that HANA_CALL_TIMEOUT will be made configurable via the cluster configuration, or that the description of the HANA_CALL_TIMEOUT parameter will be removed from the RA metadata?

**Comment by cherrylegler** [comment]
@fmherschel, I would like to follow up when will HANA_CALL_TIMEOUT be introduced as a parameter for scale-up resource agents same as scale-out resource agents?

```HANA_CALL_TIMEOUT="${OCF_RESKEY_HANA_CALL_TIMEOUT:-120}"```

**Comment by angelabriel** [comment]
> @fmherschel, I would like to follow up when will HANA_CALL_TIMEOUT be introduced as a parameter for scale-up resource agents same as scale-out resource agents?
> 
> `HANA_CALL_TIMEOUT="${OCF_RESKEY_HANA_CALL_TIMEOUT:-120}"`
@cherrylegler we are working on an ScaleUp/ScaleOut alignment and during this work we will discuss, if we will apply the solution used in ScaleOut to ScaleUp as well. So it's work in progress, but without a fixed delivery date at the moment.
