### ISSUE TITLE
No Role information collected

### ISSUE THREAD

**Issue by swetango** [SUSE/SAPHanaSR#38]
We have installed a distributed HANA system(2+1) using non shared storage and installation completed successfully.Now we are facing an issue with SAPHanaTopology resource agent, agent is active but does not collect information regarding host roles, HANA version and host details are collected correctly, we are using RedHat 8.1

**Comment by diegoakechi** [comment]
@swetango Could you provide some logs? Hard to tell with only this information.

**Comment by fmherschel** [comment]
And ... do you have SAP HANA scale-out (multiple hosts per side) or scale-up (singe node per side)?

**Comment by fmherschel** [comment]
As there is no answer to the open questions about the issue situation I am closing the issue right now.
