### ISSUE TITLE
Use 'actual_mode' instead of 'mode' when global.ini is used as fallback to detect replication mode

### ISSUE THREAD

**Issue by fdanapfel** [SUSE/SAPHanaSR#40]
During the investigation of a customer issue where the customer provoked that the fallback to retrieve the current state of System Replication by checking the global ini is used (by removing access to the 'hdb*' binaries), it was discovered that while the initial takeover after the fault has been created works. But then a takeover back to the initial node didn't work, because the resource agents weren't able to determine that the current active HANA instance was actually the primary site.

When investigating the issue together with SAP it was discovered that the reason why the second takeover didn't work was because it is actually not correct to use the 'mode' parameter in the global.ini to determine the current state of System Replication of a HANA instance.

Here's the information provided from the colleagues who were working with the customer and SAP in debugging the issue:

----
The SAPHana resource agent uses the `system_replication/mode` attribute from global.ini as a fallback if the `$hdbState` command fails. The expectation is that a takeover event updates the `mode` parameter so that it's usually a valid representation of which node is currently primary.

However, `mode` is a static parameter that does not change with a takeover event. Instead, the takeover updates the `actual mode` parameter.

The resource agent needs to be updated to query the correct parameter in the event that `$hdbState` fails. This way, it can respond more appropriately to edge-case situations like missing hdb* binaries.

Adapted from an SAP engineer in a support collaboration email:
~~~
# Before takeover
# node1 is primary, node2 is secondary
	
global.ini on node1:
  mode  = primary
  actual mode = primary
  operation_mode = logreplay

global.ini on node2:
  mode  = sync
  actual mode = sync
  operation_mode = logreplay

hdbnsutil -sr_state on node1:
  mode: primary
  operation mode: primary

hdbnsutil -sr_state on node2:
  mode: sync
  operation mode: logreplay

# After takeover/failover
# node1 is secondary, node2 is primary

global.ini on node1:
  mode  = primary
  actual mode = sync
  operation_mode = logreplay

global.ini on node2:
  mode  = sync
  actual mode = primary
  operation_mode = logreplay

hdbnsutil -sr_state on node1:
  mode: sync
  operation mode: logreplay

hdbnsutil -sr_state on node2:
  mode: primary
  operation mode: primary
~~~
Just have a look how we change the parameter values depending on the source – global.ini or hdbnsutil -sr_state. I highlighted major differences.

This behavior doesn’t depend on removing binaries, it’s normal HANA parameter change after the takeover/re-registering secondaries to new primary. Confirmation is provided in SAP Note 1999880 - FAQ: SAP HANA System Replication:

47. Why do I see deviating values in the system replication mode parameter?

The value in parameter global.ini -> [system_replication] -> mode depends on the original role of the site:

·         If site was originally configured as primary site: mode = 'primary'

·         If site was originally configured as secondary / tertiary site: mode = 'sync', 'async', ... (dependent on the system replication mode)

As a consequence the mode value can be different in two identically configured systems if a takeover happened in one system, but not in the other.

----
Is there a specific reason why the 'mode' parameter is checked instead of 'actual_mode'? If not I would like to update the SAPHana resource agent to get this fixed.

**Comment by fmherschel** [comment]
As far as I remember the "actual_mode" is not avaiable on all HANA we do support with the RA. So we would need to check in which version the new value did occur. I also have seen that change and thank you so much for your detailed investigation.

**Comment by angelabriel** [comment]
Instead of checking for the HANA version, which add the new value, we can simple enhance the 'gpKeys' variable with 'actual_mode' and check after 'getParameter.py' if the value of 'actual_mode' is empty, because 'getParameter.py' returns non-existing keys as 'empty'. In this case we still use the value of 'mode' key as fallback of the fallback :-)

**Comment by fmherschel** [comment]
I like this idea ;-)

**Comment by fdanapfel** [comment]
@angelabriel @fmherschel: thanks a lot for the quick response and for taking the suggested change into consideration.

I also like the idea suggested by @angelabriel and will take it into account when I try to develop the patch for this.

But before I start working on the patch I have two more questions:
- the 'gpkeys' variable is currently set up so that getParameter.py will also return the value of the'site_name' and 'side_id' parameters: https://github.com/SUSE/SAPHanaSR/blob/master/ra/SAPHana#L1035
But as far as I can see the values of 'site_name' and side_id' returened by this specific query are then never used. Would it therefore be safe to assume that the gpkeys variable could be changed to only query for 'actual_mode' or 'mode'? 

- the SAPHanaTopology resource agent also checks the Replication mode in the 'sht_init' function: https://github.com/SUSE/SAPHanaSR/blob/master/ra/SAPHanaTopology#L554 (and following lines)
I guess this check would also have to be changed to query the 'actual_mode' and 'mode' parameters, correct?
One thing that is strange to me though about the code in the SAPHanaTopology resource agent is that while it tries to set the value of the 'srmode' variable in the for loop, it then later on tries to set it again after the for loop: https://github.com/SUSE/SAPHanaSR/blob/master/ra/SAPHanaTopology#L589
Is there a specific reason for that?

**Comment by fdanapfel** [comment]
The customer who actually raised this issue now reported back that the change suggested by SAP to use 'actual_mode' instead of 'mode' when checking the replication mode in the global.ini fixed their issue.

@fmherschel @angelabriel Since you've suggested a couple of different solutions for this issue would it be possible for you to have a call in the near future (maybe next week) where we could discuss how to move forward with creating an official patch for this issue?

**Comment by fdanapfel** [comment]
I've now checked how this is handled by the resource agents for the HANA Scale-Out System Replication HA solution (https://github.com/SUSE/SAPHanaSR-ScaleOut), but as far as I can se there the 'mode' attribute from the global.ini isn't used at all as a fallback.

So maybe simply dropping this code might be an option as well?

**Comment by rbrunt007** [comment]
Any update on this issue and how the script will handle this in the future?

**Comment by angelabriel** [comment]
Hi Rich,
commit https://github.com/SUSE/SAPHanaSR/commit/ec9fd4e526e572fe9bc0070186fa584b032eac22 contains the fix for this issue and will be part of the next maintenance update. But as I need to investigate and may be fix some additional bugs I can not give you a reliable release date yet.

**Comment by fdanapfel** [comment]
@angelabriel Thanks for providing a fix for this via commit https://github.com/SUSE/SAPHanaSR/commit/ec9fd4e526e572fe9bc0070186fa584b032eac22 . Our customer now tested this fix and verified that it resolves their issue.

Therefore I'm closing this issue.
