### ISSUE TITLE
FULL_SR_STATUS changed from 60s to 5s

### ISSUE THREAD

**Issue by khokarv** [SUSE/SAPHanaSR#42]
I would like to ask if we can a variable instead of hard coded value and second in our shop systems are getting SFAIL production due to less value. can we keep 60s or why this has been changed from 60s to 5s ? 

-    FULL_SR_STATUS=$(HANA_CALL --timeout 60 --cmd "systemReplicationStatus.py $siteParam" 2>/dev/null); srRc=$?
+    FULL_SR_STATUS=$(HANA_CALL --timeout 5 --cmd "systemReplicationStatus.py $siteParam" 2>/dev/null); srRc=$?

Thanks, Viney

**Comment by fmherschel** [comment]
The timeout was shortened to close the gap of possible loss of data. Best practice is to also implement the HA/DR python hook, if you are already on SAP HANA 2.0 (>= SPS3).
If you question is regarding a productive situation you need to contact your professional support by your OS/HA vendor.
